#!/bin/bash 
wget https://dl3.pling.com/api/files/download/j/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE2Mzc0NDc0NDMiLCJ1IjpudWxsLCJsdCI6ImRvd25sb2FkIiwicyI6IjA5ZDRiYTIyNWYyNjE5OTNhNmQzYTFmYzU2ZjQ3ZjEzYzBkMzRhNWYwYTJhNDYyZmVmNmQ4ZWMyNmJhOTMzNmNkMGY0ZWMyYjNjOTQ1NmM2ZGM3YjU4ZDI4ZDU3YTdhNTFiODRmYTA4MTkwNGQyZTMxNmZkMTNmYjdkNDE1N2YwIiwidCI6MTYzOTc2MDUxMSwic3RmcCI6IjliZDZmYzAxZTBhMjRkNWY1OTJmM2I1ODU1N2UxY2MzIiwic3RpcCI6IjE5Ny4yMzEuMjAxLjE5NiJ9.la2nXUYD_pxyRB-qC-suNujOAn43XCqe5mTqS--X_wQ/candy-icons.tar.xz
axel -n 10 https://dl3.pling.com/api/files/download/j/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE2MzkzNDQ3OTYiLCJ1IjpudWxsLCJsdCI6ImRvd25sb2FkIiwicyI6IjA5NGJkMzg5YTljNjhkNzY3ZmZmNGU2Mzk0NjcyMDQ2MDJlNjkxMWZjNjQ0M2RmZTMyYWZiYWVmNTY0MWUzM2IwMTVkNzVhYWFlMzI5ZTE1YmZiOTgzZjc5MTExNGQ4ODhlMjEzZTA1ZGRkY2ZiMmExNjBjYzU5ODU0NWVjODVjIiwidCI6MTYzOTc2MDU0NCwic3RmcCI6IjliZDZmYzAxZTBhMjRkNWY1OTJmM2I1ODU1N2UxY2MzIiwic3RpcCI6IjE5Ny4yMzEuMjAxLjE5NiJ9.9GpQWxausOZWTgGSsC5HM6hFbTTWVaabPBDRWzzoles/Sweet-Dark.tar.xz
tar -xf Sweet-Dark.tar.xz
tar -xf candy-icons.tar.xz
mv Sweet-Dark /usr/share/themes
mv candy-icons /usr/share/icons

